/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AppTemplatesRouteImport } from './routes/_app/templates'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppScanRouteImport } from './routes/_app/scan'
import { Route as AppPlanRouteImport } from './routes/_app/plan'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCampaignsRouteImport } from './routes/_app/campaigns'
import { Route as AppContactsIndexRouteImport } from './routes/_app/contacts.index'
import { Route as AppTemplatesCreateRouteImport } from './routes/_app/templates.create'
import { Route as AppExtractedContactIdRouteImport } from './routes/_app/extracted.$contactId'
import { Route as AppContactsContactIdRouteImport } from './routes/_app/contacts.$contactId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsRoute = AppCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsIndexRoute = AppContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesCreateRoute = AppTemplatesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppTemplatesRoute,
} as any)
const AppExtractedContactIdRoute = AppExtractedContactIdRouteImport.update({
  id: '/extracted/$contactId',
  path: '/extracted/$contactId',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsContactIdRoute = AppContactsContactIdRouteImport.update({
  id: '/contacts/$contactId',
  path: '/contacts/$contactId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaigns': typeof AppCampaignsRoute
  '/dashboard': typeof AppDashboardRoute
  '/plan': typeof AppPlanRoute
  '/scan': typeof AppScanRoute
  '/settings': typeof AppSettingsRoute
  '/templates': typeof AppTemplatesRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/contacts/$contactId': typeof AppContactsContactIdRoute
  '/extracted/$contactId': typeof AppExtractedContactIdRoute
  '/templates/create': typeof AppTemplatesCreateRoute
  '/contacts/': typeof AppContactsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campaigns': typeof AppCampaignsRoute
  '/dashboard': typeof AppDashboardRoute
  '/plan': typeof AppPlanRoute
  '/scan': typeof AppScanRoute
  '/settings': typeof AppSettingsRoute
  '/templates': typeof AppTemplatesRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/contacts/$contactId': typeof AppContactsContactIdRoute
  '/extracted/$contactId': typeof AppExtractedContactIdRoute
  '/templates/create': typeof AppTemplatesCreateRoute
  '/contacts': typeof AppContactsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/campaigns': typeof AppCampaignsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/plan': typeof AppPlanRoute
  '/_app/scan': typeof AppScanRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/templates': typeof AppTemplatesRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_app/contacts/$contactId': typeof AppContactsContactIdRoute
  '/_app/extracted/$contactId': typeof AppExtractedContactIdRoute
  '/_app/templates/create': typeof AppTemplatesCreateRoute
  '/_app/contacts/': typeof AppContactsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaigns'
    | '/dashboard'
    | '/plan'
    | '/scan'
    | '/settings'
    | '/templates'
    | '/auth/login'
    | '/auth/signup'
    | '/contacts/$contactId'
    | '/extracted/$contactId'
    | '/templates/create'
    | '/contacts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campaigns'
    | '/dashboard'
    | '/plan'
    | '/scan'
    | '/settings'
    | '/templates'
    | '/auth/login'
    | '/auth/signup'
    | '/contacts/$contactId'
    | '/extracted/$contactId'
    | '/templates/create'
    | '/contacts'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/campaigns'
    | '/_app/dashboard'
    | '/_app/plan'
    | '/_app/scan'
    | '/_app/settings'
    | '/_app/templates'
    | '/auth/login'
    | '/auth/signup'
    | '/_app/contacts/$contactId'
    | '/_app/extracted/$contactId'
    | '/_app/templates/create'
    | '/_app/contacts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scan': {
      id: '/_app/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plan': {
      id: '/_app/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns': {
      id: '/_app/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AppCampaignsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts/': {
      id: '/_app/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AppContactsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates/create': {
      id: '/_app/templates/create'
      path: '/create'
      fullPath: '/templates/create'
      preLoaderRoute: typeof AppTemplatesCreateRouteImport
      parentRoute: typeof AppTemplatesRoute
    }
    '/_app/extracted/$contactId': {
      id: '/_app/extracted/$contactId'
      path: '/extracted/$contactId'
      fullPath: '/extracted/$contactId'
      preLoaderRoute: typeof AppExtractedContactIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts/$contactId': {
      id: '/_app/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof AppContactsContactIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppTemplatesRouteChildren {
  AppTemplatesCreateRoute: typeof AppTemplatesCreateRoute
}

const AppTemplatesRouteChildren: AppTemplatesRouteChildren = {
  AppTemplatesCreateRoute: AppTemplatesCreateRoute,
}

const AppTemplatesRouteWithChildren = AppTemplatesRoute._addFileChildren(
  AppTemplatesRouteChildren,
)

interface AppRouteChildren {
  AppCampaignsRoute: typeof AppCampaignsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppPlanRoute: typeof AppPlanRoute
  AppScanRoute: typeof AppScanRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTemplatesRoute: typeof AppTemplatesRouteWithChildren
  AppContactsContactIdRoute: typeof AppContactsContactIdRoute
  AppExtractedContactIdRoute: typeof AppExtractedContactIdRoute
  AppContactsIndexRoute: typeof AppContactsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCampaignsRoute: AppCampaignsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppPlanRoute: AppPlanRoute,
  AppScanRoute: AppScanRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTemplatesRoute: AppTemplatesRouteWithChildren,
  AppContactsContactIdRoute: AppContactsContactIdRoute,
  AppExtractedContactIdRoute: AppExtractedContactIdRoute,
  AppContactsIndexRoute: AppContactsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
